#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

for ((wLow = -2; wLow < 3; wLow = wLow + 2))

do

for ((wHigh = 6; wHigh < 17; wHigh = wHigh + 1))

do


make
./bgfgGraphs -2 2.5 $wLow $wHigh
make clean

done

done

echo "Done running bash script"
