#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

for ((wLow = 0; wLow < 1; wLow = wLow + 1))

do

for ((wHigh = 6; wHigh < 21; wHigh = wHigh + 1))

do


make
./fig33 $wLow $wHigh
make clean

done

done

echo "Done running bash script"
